# Generated by Django 3.1.6 on 2021-02-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_text',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='text',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
